### ISSUE TITLE
Versions incorrectly constrains name

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/automation-sql#26]
When first developed, the assumption was that `Versions` were hard concepts. It turns on that the name of the instance can be changed to anything a developer wants.

https://github.com/ritterim/automation-sql/blob/development/src/Core/LocalDb.cs#L72-L73
___

The solution should be to drop the validation and let users set the value to whatever makes sense.

**Comment by kendaleiv** [comment]
Do we want to remove the concept of `Versions` and default to `(localdb)\MSSQLLocalDB` -- but, allow that to be overridden as necessary?

See http://thebillwagner.com/Blog/Item/2015-02-05-VersionindependentlocalDBinVisualStudio2015.
