### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by NPadrutt** [ritterim/automation-sql#45]
Hi
I found your library and really like it. Are there any plans to move it to / support .net standard?

Thanks
Nino

EDIT: I had a quick view. The only thing who could be an issue is the Registry for accessing the installed version of the Local DB. If there is another solution for that a port would be easy it seems.

**Comment by kendaleiv** [comment]
There aren't any current plans to support .NET standard. Would you be interested in creating a pull request? A community member added support to https://github.com/ritterim/automation-storage-emulator and was merged and released, if you'd like to a reference.

**Comment by NPadrutt** [comment]
I think the question is, how we can detect the installed version of the local DB. I will have a look at that when I have a bit more time.

**Comment by CasperWSchmidt** [comment]
I need this feature as well so I took the liberty of doing the work myself. I have created #46. This is my first multi-target contribution so I might have forgotten something.
Also most tests failed on my local machine since I only have version 13 installed locally.

**Comment by kendaleiv** [comment]
Released in https://www.nuget.org/packages/RimDev.Automation.Sql/1.0.0
