### ISSUE TITLE
Change Version to InstanceName

### ISSUE THREAD

**Issue by CasperWSchmidt** [ritterim/automation-sql#55]
Continuing what was started in #51:

I suggest that Version is renamed to InstanceName since the string really has nothing to do with the version of LocalDB running. As stated in https://github.com/ritterim/automation-sql/pull/51#issuecomment-442448276 the instance name and version is correlated by coincidence (or "carefully" choosing the instance name).

For anyone using the package they might get confused about the version number being specified including "v" prefix. Especially so with the new feature in #51 where the version is currently found as Version.Replace("v", "") - not very elegant and bulletproof :)

After renaming Version to InstanceName the next suggestion could be to have Version as well (being a string/enum with possible values "11.0", "12.0" and "13.0" (without "v"-prefix). Default could be kept like "v11.0" for InstanceName and "11.0" for Version to stay somewhat backwards compatible.

**Comment by CasperWSchmidt** [comment]
I can make a PR if wanted. But I would like to have the discussion/agreement beforehand :)

**Comment by kendaleiv** [comment]
If it's an optional parameter and opt-in like #51 then sounds good. I don't have any personal stake in this feature, but if it's helpful to anyone then I'm all for it.

Feel free to submit a PR and we'll get it released.

**Comment by CasperWSchmidt** [comment]
@kendaleiv the problen is that renaming could be a breaking change for anyone specifying the version/instance name explicitly. But since 1.0.0 introduced another breaking change and probably no one (except me) uses that it might be okay to do the renaming in 1.0.4 or 1.1.0 😊

Introducing a new parameter named version will be confusing no matter what, if you used any version of this package prior to the suggested changes.

**Comment by khalidabuhakmeh** [comment]
I would agree with renaming it. When this library was first created, I didn't realize that the `v13.0` was a default name instance that a localdb install would be given, but is completely arbitrary.

**Comment by CasperWSchmidt** [comment]
@kendaleiv The thing is, optional parameters can be used as:

```
var db = new LocalDB(version: "test")
```
That way any other optional parameters can be omitted and the compiler will still be able to know which of the parameters are actually set.
Any program using this named-parameter style will stop working if the parameter is renamed to instanceName - that is why I see it as a potential breaking change :)
I will try to make time for a PR with the renaming and a new optional constructor parameter "databaseVersion" (to avoid naming-conflicts with the existing "version")

**Comment by kendaleiv** [comment]
Related change released in https://www.nuget.org/packages/RimDev.Automation.Sql/1.2.0
